apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app   # ✅ Lowercase name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/spring-boot-app.git'
    targetRevision: main
    path: spring-boot-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
