apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rineeth-R/End-to-End-CI-CD-Pipeline.git'  # ✅ Replace with your actual repo
    targetRevision: master
    path: spring-boot-app-manifests 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

